---
- name: merge dictionaries
  block:
  - name: register default vars
    include_vars:
      file: ../../darexsu.zabbix_gui/defaults/main.yml
      name: zabbix_gui_default_vars

  - name: merge default and new dictionaries
    set_fact:
      "{{ item.key }}": "{{ zabbix_gui_default_vars[item.key] | combine(merge[item.key], recursive=True)}}"
    when: zabbix_gui_default_vars[item.key] is defined
    with_dict: "{{ merge }}"

  - name: combine defaults vars with merge dictionary
    set_fact:
      merge: "{{ zabbix_gui_default_vars | combine(merge, recursive=True)}}"
  when: merge is defined

- name: zabbix_gui role is disabled
  meta: end_play
  when: not zabbix_gui.enabled

- name: include zabbix_gui install
  include_tasks: ./tasks/zabbix_gui/install/zabbix_gui__install_{{ ansible_os_family }}.yml
  when: zabbix_gui_install.enabled

- name: gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: include zabbix_gui config
  include_tasks: ./tasks/zabbix_gui/config/zabbix_gui__config.yml
  when: (zabbix_gui_install['packages'][ansible_os_family]) in ansible_facts.packages

- name: include php tasks
  include_tasks: ./tasks/php/zabbix_gui__php.yml
  when: php.enabled

- name: include apache tasks
  include_tasks: ./tasks/apache/zabbix_gui__apache.yml
  when: apache.enabled

- name: include nginx tasks
  include_tasks: ./tasks/nginx/zabbix_gui__nginx.yml
  when: nginx.enabled

- name: include firewalld tasks
  include_tasks: ./tasks/firewalld/zabbix_gui__firewalld.yml
  when: firewalld.enabled