---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Unnessessary command
      ansible.builtin.shell:
        cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
      when: lookup('env', 'ANSIBLE_COMMAND') | length > 0

  vars:
    merge:
      # Zabbix_GUI
      zabbix_gui:
        enabled: true
        src: "third_party"
        version: "6.0"
        server_name: "Zabbix server"
        db_type: "MYSQL"
        db_port: "3306"
        db_server: "localhost"
        db_name: "zabbix"
        db_user: "zabbix"
        db_password: "change_me"
      # Zabbix_GUI -> install
      zabbix_gui_install:
        enabled: true
      # Zabbix_GUI -> config
      zabbix_gui_config:
        enabled: true

      # PHP
      php:
        enabled: true
        version: "7.4"
        src: "third_party"
      # PHP -> install
      php_install:
        enabled: true
      # PHP -> config
      php_fpm:
        zabbix_conf:
          enabled: true

      # Apache
      apache:
        enabled: true
      # Apache -> install
      apache_install:
        enabled: true
      # Apache -> config -> apache.conf
      apache_conf:
        enabled: true
      # Apache -> config -> modules
      apache_modules:
        enabled: true
        mods_enabled: [proxy, proxy_fcgi]
        mods_disabled: []
      # Apache -> config -> virtualhost.conf
      apache_virtualhost:
      # Apache -> config -> delete default virtual_host
        default_conf:
          enabled: true
          state: "absent"
      # Apache -> config -> add zabbix virtual_host
        zabbix_conf:
          enabled: true

      # FirewallD
      firewalld:
        enabled: true
      # FirewallD -> rules
      firewalld_rules:
        service_http:
          enabled: true
        service_https:
          enabled: true

  tasks:
    - name: include role darexsu.zabbix_gui
      include_role:
        name: darexsu.zabbix_gui